### PR TITLE
less 1.3.3 upgrade

### PR DESCRIPTION
**Pull request by emecell**
Hi, 

I updated less.js to 1.3.3 and fixed some of the tests. Looks like less will remove obvious duplicate styles now and capitalize IE filters.

-R

### CODE REVIEW

**Comment by verglor** [comment]
+1

**Comment by ptcc** [comment]
+1

**Comment by kevinroberts** [comment]
+1

**Comment by walterg2** [comment]
@cpopov I saw this update was made (before I had a chance to fork and make the change myself) and I was wondering when you anticipated updating the Central Maven Repo with this update? I see it's been made and I've tested locally that it resolves my issue with trying to compile bootstrap LESS files in my application.

Any help is MUCH appreciated!

**Pull request merged**
